### ISSUE TITLE
add verbose mode option to show struct size info even if it cannot be optimized

### ISSUE THREAD

**Issue by omoerbeek** [orijtech/structslop#32]
Thanks for this great tool! I do have an feature request, though.

To get a feeling of how big a struct is, I'd like to program to be able to print info even if it cannot be optimized. I could not find an option for that.

**Comment by odeke-em** [comment]
Thank you for the feature request @omoerbeek and welcome to Orijtech’s projects! Sounds like a plan to me. I shall kindly page my colleague @cuonglm; let’s please add a —verbose flag that prints out the natural size and size class too so for example: `<file>:<line>: 56 (size class 64)`
