### ISSUE TITLE
Using -fix does not seem to apply fixes

### ISSUE THREAD

**Issue by Jacalz** [orijtech/structslop#37]
I was testing this on https://github.com/fyne-io/fyne and adding `-fix` does not seem to do anything. Double checking with git just seems to indicate that no files have been changed.

![image](https://user-images.githubusercontent.com/25466657/99254590-e0255f00-2812-11eb-90c4-98a3432f549f.png)

**Comment by cuonglm** [comment]
Yes, it's intentional.

We did have `-fix` work in the past, but we can't find a way to preserve struct field comment, so we removed it.

**Comment by sumerc** [comment]
Hello!

I am not an expert on Go but do you mean:

```
struct {
x int  // a comment
y int 
z int
}
```

cannot be restructured into something like?:
```
struct {
y int
x int  // a comment
z int
}
```

**Comment by cuonglm** [comment]
@sumerc Yes, the comment will be lost, so it's only:

```
struct {
    y int
    x int
}
```

**Comment by odeke-em** [comment]
@sumerc thanks for the question! @cuonglm means that shuffling around
fields which could be of the form:
struct {
    // This is a comment
    i1, i2 int64 // which one is that
    ...
}

In whatever form, if they need to be arranged needs to work correctly
before we go on, and it was easier to punt that intentional, launch, get
traction and later fix it — this ensures that we can incrementally add
features and not block releases.

**Comment by sumerc** [comment]
I see.

 > i1, i2 int64 // which one is that

I am not sure if above is solvable at all. Maybe `-fix` should warn that it cannot do that kind of thing with a proper message.

For the other problem of comment being lost is somewhat interesting... I could not see why `ast` cannot detect an inline comment. In any case, I think it could be doable somehow by copying the rest of the line together with the field itself. Just thinking out loudly...

**Comment by cuonglm** [comment]
@sumerc here's relevant issue https://github.com/golang/go/issues/20744
