### ISSUE TITLE
What is the advantage of structslop over golangci-lint's 'maligned' ?

### ISSUE THREAD

**Issue by rockdaboot** [orijtech/structslop#45]
Maybe you can put a section of pros and cons into the README.md ?

**Comment by hairyhenderson** [comment]
According to the [`maligned` repo](https://github.com/mdempsky/maligned), it's deprecated now, and https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment is recommended instead.

**Comment by jschaf** [comment]
I came to structslop from fieldalignment because fieldalignment doesn't provide hints on how to fix it.

**Comment by fa-gb** [comment]
![image](https://github.com/orijtech/structslop/assets/129736719/7096ceb6-34cf-4aba-86b9-d3670161539f)
is this work?
