### ISSUE TITLE
structslop: internal error: package "context" without types was imported

### ISSUE THREAD

**Issue by robdeacon** [orijtech/structslop#57]
OS: Windows 10 64bit
Go version: 1.18.4
structslop v0.0.6
Installed using go get i.e modules
My target project mod is using Go version 1.18

Usage: within target project
structslop  ./

Expected outcome:
Suggestions or nothing if no suggestions.

Actual outcome:
structslop: internal error: package "context" without types was imported from "docgenapi [docgenapi.test]"

Maybe i'm reading this wrong perhaps? The message doesn't give any useful information about how to correct my code. Not sure what i'm meant to do from this.

Any advice appreciated.

**Comment by dominikstebel** [comment]
The same happens for the `fmt` package.

_structslop: internal error: package "fmt" without types was imported from "command-line-arguments"_

**Comment by morganhein** [comment]
I am 20% confident this is an issue due to generics, as i'm getting the same issue for other stdlib imports (which work otherwise), and the error seems to signify typing information is missing... so.... just going to avoid this check until it's fixed.

**Comment by kirbyquerby** [comment]
I believe this was fixed in #54 but v0.0.6 was released in december 2020. I've created https://github.com/orijtech/structslop/releases/tag/v0.0.7 , which should hopefully work. Feel free to reopen if it still doesn't work.
