### ISSUE TITLE
is this linter compatible with Go 1.20+ ?

### ISSUE THREAD

**Issue by atc0005** [orijtech/structslop#58]
@odeke-em 

I enabled this linter in a Go 1.19 Docker image (`golang:1.19.7`) without issue, but for a Go 1.20 image (`golang:1.20.2`) I get this error:

> `structslop: internal error: package "errors" without types was imported from "github.com/..."`

To reproduce:

1. `docker image pull golang:1.20.2`
2. `docker container run -it --rm golang:1.20.2`
3. `git clone https://github.com/atc0005/check-whois`
4. `cd check-whois`
5. `go install github.com/orijtech/structslop/cmd/structslop@v0.0.7`
   - same result as `go install github.com/orijtech/structslop/cmd/structslop@latest` , but noting specific version for clarity
6. `structslop ./...`

Output:

```console
root@6c4091e45d1e:/go/check-whois# structslop ./...
structslop: internal error: package "errors" without types was imported from "github.com/atc0005/check-whois/internal/domain"
```

This produces no errors and no output:

1. `docker image pull golang:1.19.7`
2. `docker container run -it --rm golang:1.19.7`
3. `git clone https://github.com/atc0005/check-whois`
4. `cd check-whois`
5. `go install github.com/orijtech/structslop/cmd/structslop@v0.0.7`
6. `structslop ./...`

**Comment by tarnowsc** [comment]
seems that simple update of dependencies solves the issue:

```
module github.com/orijtech/structslop

go 1.18

require (
	github.com/dave/dst v0.27.2
	golang.org/x/tools v0.8.0
)

require (
	golang.org/x/mod v0.10.0 // indirect
	golang.org/x/sys v0.7.0 // indirect
)
```

**Comment by atc0005** [comment]
@tarnowsc Thanks for the feedback.

@odeke-em Will you accept a PR that provides these dependency updates?

**Comment by kirbyquerby** [comment]
We'll accept a PR (sorry for not actively responding to this issue). https://github.com/orijtech/structslop/pull/54 is a good example of which files need to be changed.

**Comment by atc0005** [comment]
@kirbyquerby 

Submitted PR #59 for review.

**Comment by kirbyquerby** [comment]
Thanks @atc0005 for the PR updating to Go 1.20. I've created https://github.com/orijtech/structslop/releases/tag/v0.0.8 which should hopefully work. Feel free to reopen if there are still issues.

**Comment by atc0005** [comment]
@kirbyquerby Thanks!
